import {
  buildAttendanceReportFileName,
  renderMyAttendanceReportPdf
} from '../src/utils/pdfReportRenderer.js';

const payload = {
  report_metadata: {
    title: 'My Attendance Report',
    brand: 'Infinite Track',
    generated_at: '2026-07-07T00:00:00.000Z',
    generated_by: 'Infinite Track Backend',
    timezone: 'Asia/Jakarta',
    source_of_truth_notice: 'Generated from backend attendance records as the source of truth.'
  },
  user: {
    id: 42,
    full_name: 'Febri User',
    nip_nim: 'NIP-42',
    role: 'User',
    position: 'Engineer',
    division: 'Information Systems'
  },
  period: {
    type: 'monthly',
    display_label: 'Jul 2026',
    start_date: '2026-07-01',
    end_date: '2026-07-31'
  },
  summary: {
    attendance_rate: 92,
    attendance_rate_percent: 92,
    attendance_rate_label: '92%',
    attendance_rate_note: 'Based on counted attendance days in this report.',
    expected_working_days: null,
    expected_working_days_label: 'Unavailable',
    attended_days: 18,
    total_present: 18,
    total_absent: 1,
    total_counted_days: 19,
    on_time_days: 16,
    late_days: 2,
    alpha_days: 1,
    total_work_hours: 168.5,
    total_work_hours_label: '168h 30m',
    late: 2,
    alpha: 1
  },
  status_distribution: {
    on_time: { key: 'on_time', label: 'On Time', count: 16, percentage: 84 },
    late: { key: 'late', label: 'Late', count: 2, percentage: 11 },
    alpha: { key: 'alpha', label: 'Alpha', count: 1, percentage: 5 }
  },
  mode_distribution: {
    wfo: { count: 1, included: true, label: 'WFO', percentage: 100 },
    wfa: { count: 0, included: true, label: 'WFA', percentage: 0 },
    wfh: { count: 0, included: false, label: 'WFH', percentage: null, note: 'Needs Verification: INF-164' }
  },
  timeline: [
    {
      attendance_date: '2026-07-01',
      mode_label: 'WFO',
      time_range: '08:00 - 17:00',
      work_hour: '08:00',
      status_label: 'On Time',
      location_label: 'Kantor Utama'
    }
  ],
  empty_state: { is_empty: false, message: null }
};

describe('personal attendance PDF renderer', () => {
  it('renders a PDF buffer with required report sections and no excluded product content', () => {
    const pdf = renderMyAttendanceReportPdf(payload);
    const text = pdf.toString('utf8');

    expect(Buffer.isBuffer(pdf)).toBe(true);
    expect(text.startsWith('%PDF-')).toBe(true);
    expect(text).toContain('Infinite Track');
    expect(text).toContain('Personal Attendance Report');
    expect(text).toContain('PDF Ready');
    expect(text).toContain('Personal report');
    expect(text).toContain('NIP-42');
    expect(text).toContain('Information Systems');
    expect(text).toContain('Attendance Rate');
    expect(text).toContain('92%');
    expect(text).toContain('On Time Days');
    expect(text).toContain('Late Days');
    expect(text).toContain('Alpha Days');
    expect(text).toContain('Total Work Hours');
    expect(text).toContain('Attendance Status Distribution');
    expect(text).toContain('Work Mode Distribution');
    expect(text).toContain('Monthly Attendance History');
    expect(text).toContain('Date | Check In | Check Out | Work Hours | Status | Mode | Location');
    expect(text).toContain('Generated by Infinite Track');
    expect(text).not.toContain('This report summarizes validated attendance activity');
    expect(text).not.toContain('Personal Insight');
    expect(text).not.toContain('Smart Reminder');
    expect(text).not.toContain('Company Services');
    expect(text).not.toContain('Avg Discipline');
    expect(text).not.toContain('Discipline Score Range');
    expect(text).not.toContain('risk indicators');
  });

  it('builds the canonical monthly filename', () => {
    expect(buildAttendanceReportFileName(payload)).toBe('infinite-track-attendance-report-2026-07.pdf');
  });
});
