const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const LEFT_MARGIN = 48;
const TOP_MARGIN = 56;
const BOTTOM_MARGIN = 56;
const LINE_HEIGHT = 15;
const MAX_LINE_CHARS = 92;

const escapePdfText = (value) => {
  return String(value ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
    .replace(/[\r\n]+/g, ' ');
};

const normalizeText = (value) => String(value ?? '—').replace(/\s+/g, ' ').trim() || '—';

const wrapText = (value, maxChars = MAX_LINE_CHARS) => {
  const words = normalizeText(value).split(' ');
  const lines = [];
  let current = '';

  for (const word of words) {
    if (!current) {
      current = word;
      continue;
    }

    if (`${current} ${word}`.length > maxChars) {
      lines.push(current);
      current = word;
    } else {
      current = `${current} ${word}`;
    }
  }

  if (current) lines.push(current);
  return lines.length > 0 ? lines : ['—'];
};

const makeTextLine = (text, x, y, size = 10) => {
  return `BT /F1 ${size} Tf ${x} ${y} Td (${escapePdfText(text)}) Tj ET`;
};

const currentPage = (pages) => pages[pages.length - 1];

const ensurePageSpace = (pages, requiredHeight = LINE_HEIGHT) => {
  if (currentPage(pages).cursorY - requiredHeight < BOTTOM_MARGIN) {
    pages.push({ lines: [], cursorY: PAGE_HEIGHT - TOP_MARGIN });
  }
};

const addWrappedLine = (pages, text, options = {}) => {
  const size = options.size || 10;
  const lineHeight = options.lineHeight || LINE_HEIGHT;
  const indent = options.indent || 0;
  const maxChars = options.maxChars || MAX_LINE_CHARS;

  for (const line of wrapText(text, maxChars)) {
    ensurePageSpace(pages, lineHeight);
    const page = currentPage(pages);
    page.lines.push(makeTextLine(line, LEFT_MARGIN + indent, page.cursorY, size));
    page.cursorY -= lineHeight;
  }
};

const addGap = (pages, gap = 8) => {
  currentPage(pages).cursorY -= gap;
};

const addRule = (pages) => {
  addWrappedLine(pages, '────────────────────────────────────────────────────────────────────────────', {
    size: 8,
    lineHeight: 10,
    maxChars: 100
  });
};

const addSectionTitle = (pages, title) => {
  addGap(pages, 6);
  addWrappedLine(pages, title, { size: 13, lineHeight: 18 });
};

const addLabelValue = (pages, label, value, options = {}) => {
  addWrappedLine(pages, `${label}: ${value ?? '—'}`, {
    size: options.size || 10,
    lineHeight: options.lineHeight || LINE_HEIGHT,
    indent: options.indent || 0,
    maxChars: options.maxChars || MAX_LINE_CHARS
  });
};

const addMetric = (pages, label, value, helper) => {
  addWrappedLine(pages, `${label}: ${value ?? '—'}${helper ? ` — ${helper}` : ''}`, {
    size: 10,
    lineHeight: 14,
    indent: 8,
    maxChars: 100
  });
};

const formatDateLabel = (value) => {
  if (!value) return '—';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return String(value);
  return date.toISOString().slice(0, 10);
};

const formatDistributionRows = (distribution = {}) => {
  return Object.entries(distribution)
    .filter(([, item]) => item && (item.included !== false || item.count > 0))
    .map(([key, item]) => {
      const percentage = item.percentage == null ? 'N/A' : `${item.percentage}%`;
      const note = item.note ? ` — ${item.note}` : '';
      return `${item.label || key}: ${item.count ?? 0} (${percentage})${note}`;
    });
};

const addHeader = (pages, payload) => {
  addWrappedLine(pages, 'INFINITE TRACK', { size: 17, lineHeight: 20 });
  addWrappedLine(pages, 'Personal Attendance Report', { size: 15, lineHeight: 19 });
  addWrappedLine(pages, 'PDF Ready • Personal report', { size: 10, lineHeight: 14 });
  addRule(pages);

  addWrappedLine(pages, payload.user.full_name || 'User name unavailable', { size: 13, lineHeight: 17 });
  addWrappedLine(
    pages,
    [payload.user.nip_nim, payload.user.role].filter(Boolean).join(' • ') || 'NIP/NIM or role unavailable',
    { size: 10, lineHeight: 14 }
  );
  addWrappedLine(
    pages,
    [payload.user.position, payload.user.division].filter(Boolean).join(' • ') || 'Position or division unavailable',
    { size: 10, lineHeight: 14 }
  );
  addGap(pages, 6);

  addLabelValue(pages, 'Period', payload.period.display_label);
  addLabelValue(pages, 'Generated on', formatDateLabel(payload.report_metadata.generated_at));
  addLabelValue(pages, 'Generated by', payload.report_metadata.generated_by || 'Infinite Track Backend');
  addLabelValue(pages, 'Data source', 'Backend attendance records');
  addRule(pages);
};

const addSummary = (pages, summary) => {
  addSectionTitle(pages, 'Report Summary');
  addMetric(pages, 'Attendance Rate', summary.attendance_rate_label, 'Overall attendance');
  addMetric(pages, 'On Time Days', `${summary.on_time_days ?? 0} days`, 'Days with on-time check-in');
  addMetric(pages, 'Late Days', `${summary.late_days ?? summary.late ?? 0} days`, 'Days with late check-in');
  addMetric(pages, 'Alpha Days', `${summary.alpha_days ?? summary.alpha ?? 0} days`, 'Days without valid attendance');
  addMetric(pages, 'Counted Days', `${summary.total_counted_days ?? 0} days`, 'Present + alpha days');
  addMetric(pages, 'Total Work Hours', summary.total_work_hours_label || summary.total_work_hours, 'Total productive work hours');
  addMetric(pages, 'Expected Working Days', summary.expected_working_days_label || summary.expected_working_days || 'Unavailable');
};

const addDistributions = (pages, payload) => {
  addSectionTitle(pages, 'Your Statistics');
  addWrappedLine(pages, 'Attendance Status Distribution', { size: 11, lineHeight: 15, indent: 4 });
  formatDistributionRows(payload.status_distribution).forEach((line) => addWrappedLine(pages, line, { indent: 12, lineHeight: 13 }));
  addGap(pages, 4);
  addWrappedLine(pages, 'Work Mode Distribution', { size: 11, lineHeight: 15, indent: 4 });
  formatDistributionRows(payload.mode_distribution).forEach((line) => addWrappedLine(pages, line, { indent: 12, lineHeight: 13 }));
};

const addTimeline = (pages, payload) => {
  addSectionTitle(pages, 'Monthly Attendance History');
  addWrappedLine(pages, 'Date | Check In | Check Out | Work Hours | Status | Mode | Location', {
    size: 9,
    lineHeight: 13,
    maxChars: 110
  });
  addRule(pages);

  if (payload.empty_state.is_empty) {
    addWrappedLine(pages, payload.empty_state.message, { indent: 8 });
    return;
  }

  payload.timeline.forEach((row) => {
    addWrappedLine(
      pages,
      `${row.attendance_date} | ${row.time_in || '--:--'} | ${row.time_out || '--:--'} | ${row.work_hour || '—'} | ${
        row.status_label || '—'
      } | ${row.mode_label || '—'} | ${row.location_label || 'Location unavailable'}`,
      { size: 9, lineHeight: 13, maxChars: 112 }
    );
  });
};

const addFooters = (pages, payload) => {
  pages.forEach((page, index) => {
    page.lines.push(makeTextLine('Generated by Infinite Track', LEFT_MARGIN, 34, 8));
    page.lines.push(makeTextLine(`Generated timestamp: ${payload.report_metadata.generated_at}`, LEFT_MARGIN, 23, 8));
    page.lines.push(makeTextLine(`Page ${index + 1} of ${pages.length}`, PAGE_WIDTH - 105, 23, 8));
  });
};

const buildPdfObjects = (pages) => {
  const objects = [];
  const fontObjectId = 3 + pages.length * 2;
  objects.push('<< /Type /Catalog /Pages 2 0 R >>');

  const pageObjectIds = pages.map((_, index) => 3 + index * 2);
  objects.push(`<< /Type /Pages /Kids [${pageObjectIds.map((id) => `${id} 0 R`).join(' ')}] /Count ${pages.length} >>`);

  pages.forEach((page, index) => {
    const pageObjectId = 3 + index * 2;
    const contentObjectId = pageObjectId + 1;
    const stream = page.lines.join('\n');

    objects.push(
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 ${fontObjectId} 0 R >> >> /Contents ${contentObjectId} 0 R >>`
    );
    objects.push(`<< /Length ${Buffer.byteLength(stream, 'utf8')} >>\nstream\n${stream}\nendstream`);
  });

  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
  return objects;
};

const serializePdf = (objects) => {
  let pdf = '%PDF-1.4\n';
  const offsets = [0];

  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(pdf, 'utf8'));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, 'utf8');
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, 'utf8');
};

export const buildAttendanceReportFileName = (payload) => {
  const monthKey = String(payload.period.start_date || '').slice(0, 7) || 'custom-period';
  return `infinite-track-attendance-report-${monthKey}.pdf`;
};

export const renderMyAttendanceReportPdf = (payload) => {
  const pages = [{ lines: [], cursorY: PAGE_HEIGHT - TOP_MARGIN }];

  addHeader(pages, payload);
  addSummary(pages, payload.summary);
  addDistributions(pages, payload);
  addTimeline(pages, payload);
  addFooters(pages, payload);

  return serializePdf(buildPdfObjects(pages));
};
